from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D
gate='''The complete force, suffix recurrence and classical Vandermonde/binomial identities are existing inputs. Focused local searches located the fixed-precision binary contacts and old central formulas, but no exact high-sector endpoint factorization or computed rational p380 limit. The coordinator has now independently authored and executed a9216-term exact rational evaluation, with191 coefficientwise crosschecks and exact residuals; its code and compact hashed receipt are supplied. This is a finite mathematical application, not a claim of general novelty. Primary overlap is Granville, NIST DLMF18.2, Rivoal JTNB DOI10.5802/jtnb.914, and the already opened fixed-target approximation thesis arXiv:0903.0086; none automatically establishes the new actual compensated scalar.'''

make('A5',12,'''The coordinator has PERSONALLY evaluated your exact finite rational expression5.2: Z=p380*(-3)=0 EXACTLY, using all9216 terminating central summands, independently implemented polynomial convolution and triangular inverse, equality at every191 high-sector coefficient, and exact inverse residuals. The compact receipt and complete personally authored code are attached; the large rational artifact is hashed, not pasted because of the input ceiling. A further exact finite pattern is p_(190+m)=B190*(189)_falling_m for every0<=m<=190, hence the final zero. Do not treat this finite pattern as a proved infinite law. Your endpoint factorization and uniform Lipschitz theorem are NEW pending A4 review, which is now assigned. Advance beyond the individual obstruction: derive the analytic/general negative-integer high-sector truncation law, then use the resulting quantitative local factor to control ALL dangerous high-shift terms or a complete grouped scalar. The s380 countermechanism is no longer available if the continuation and continuity theorem pass. Determine a coefficientwise local factor hierarchy when n reaches negative integers and how its valuation pays the specific shift denominators, uniformly on actual original indices. The ultimate target remains an actual content-relative N-2S theorem or mixed relative alignment; the second full force,+1,shortened terminal block and final odd-prime gcd remain present. Do not merely announce the one compensated coefficient or repeat a computational framework. Seek a useful entire high-sector/group theorem with explicit support, losses and same-index scope. The prior path screens at139/180 are now corroborative and must not be repeated as the coefficient decision.''',
     [R/'responses/A5_turn11.md',R/'responses/A5_turn8.md',R/'responses/A5_turn7.md',O/'responses/A5_turn20.md',R/'responses/A4_turn13.md',C/'binary_limit_rational_coordinator.py',C/'binary_limit_rational_receipt.json'],gate)

make('A4',14,'''Prioritize independent audit of A5turn11's NEW exact endpoint factorization, high-sector inverse, rational-limit formula and uniform Lipschitz gain ell+3. The coordinator has independently authored and executed the finite rational calculation: p380*(-3)=0 EXACTLY, not just modulo a finite power, all9216 central summands and191 inverse coefficients/residuals checked by two implementations. The complete coordinator code and compact hashed receipt are attached. Inspect the original central formulas and all force/endpoint normalization; shared-source mistakes cannot be ruled out by two inverses alone. Decide whether this establishes the actual local compensation v2(p380*(k))>=v2(k+3)+3 and consequently removes the earlier individual-shift obstruction. The coordinator additionally found exact finite p_(190+m)=B190*(189)_falling_m for0<=m<=190; derive or correct its structural cause if possible. Also audit A3turn5's actual complete-force recurrence, three-tau strip, endpoint congruence to -2n*alternating factorial sum, exact3/7andsharper5valuations, real-window height lower bound and exponential-height compatible-cancellation example. Its actual full-column probes are attached as receipt; do not mistake finite w5 values for a universal formula. Give formula-level corrections and one concrete strengthened actual theorem. Preserve full original endpoints,+1,all-prime gcd and whole error. No proof of e+pi irrationality has been obtained.''',
     [R/'responses/A5_turn11.md',O/'responses/A5_turn20.md',R/'responses/A4_turn13.md',C/'binary_limit_rational_coordinator.py',C/'binary_limit_rational_receipt.json',C/'structural_receipts_coordinator.py',C/'normal29_constants_certificate.json',R/'responses/A3_turn5.md',R/'responses/A3_turn2.md',C/'general_endpoint_weights_receipt.json'],gate)

make('A3',6,'''Your turn5 complete recurrence, actual local endpoint valuations and height obstruction are NEW pending independent audit. The coordinator's exact full-column probes already measured w5(v0) at n15,30,105,210 as2,3,3,2; the complete source/receipt is attached. Do not assume all s5=1 have w5=2. Advance the actual short reconstruction/dual-lattice problem, preferably on a sharply specified original family n supported on3,5 or3,5,7. Your quadratic height lower bound only excludes heighto(n^(5/2)), while polynomial or subexponential candidates remain the meaningful arithmetic target. Derive structural information about the actual high digits of Theta from your recurrence, or find an actual infinite dual certificate/exclusion whose scale competes with factorial cancellation. An exponentially presented compatible weight is already known and does not settle q. The coordinator will personally compute the requested bounded recurrence/residue and n^3-window candidate checks at the four original indices, so do not wait for another enumeration or repeat uniqueness. A proof of the5adic s1 branch using a bounded polynomial expression would be useful only if tied to higher reconstruction or denominator behavior. Explore exact shifted factorial/derangement generating functions or contact adjoints that could force an actual rational reconstruction, retaining complete log-force in its final O(logn)strip. Give a non-tautological actual theorem, constructive candidate or obstruction at the required scale. Preserve the least clearer, endpoint gcd decomposition and whole same-index nonzero error.''',
     [R/'responses/A3_turn5.md',R/'responses/A3_turn4.md',R/'responses/A3_turn2.md',R/'responses/A4_turn10.md',C/'producer_weight_shift_coordinator.py',C/'general_endpoint_weights_receipt.json',C/'endpoint_extrapolant_coordinator.py'],gate)
