from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D

gate='''Focused archive search locates the accepted monic Legendre reference, second-kind Wronskian and all-degree b0 primitive-growth obstruction in MAIN_REVIEW_REGISTER and MAIN_ORTHOGONAL_REFERENCE_RECONSTRUCTION. Do not repeat these as new results. Primary NIST DLMF18.9 Legendre recurrence and14.7.4 second-kind convolution were opened: rho_n=i^(n-1)W_(n-1)(-i) and tau_n=i^n P_n(-i), so the logarithmic companion itself is classical overlap; the complete original contact-force identification still needs its normalization proof. Official arXiv2609.21051 abstract was opened: fast polynomial rational reconstruction/XGCD algorithms, not an integer moving-residue continued-fraction gap theorem. Previously checked Rowland--Yassawi prime-power automata and structured displacement algorithms remain classical overlap. The new targeted arithmetic is the actual d2 endpoint coprime factor or the compressed normalized adjoint moments, not a claim of general novelty. No equivalent specialized infinite-family law was located in the scoped archive/primary search; no exhaustive novelty claim.'''

make('A3',8,'''Your turn7 terminal-plane and forced-Wronskian derivations are pending separate audit and personally authored exact checks. Important primary overlap: your rho convolution is exactly the classical Legendre second-kind polynomial DLMF14.7.4 after tau_n=i^nP_n(-i),rho_n=i^(n-1)W_(n-1)(-i). Reuse it, no priority claim. Your new allprime inequality q_lambda>=|AB|/(|a||a-k|) gives a potentially decisive DIFFERENT target: derive/evaluate the coprime endpoint factor|AB|_(P-complement) in the actual d2 complete first column, then try to prove superexponential growth or sufficiently large exponential growth on the original15^r/105^r families. Exact endpoint u0,ub depend only on firstforce/contactmatrix and may reduce to adjacent tau or Legendre contiguous determinants; all their cancellation must be paid before growth. A lower bound on raw factorials, the denominator of omega, or a nonminimal clearer is insufficient. The attached old b0 exclusion and reference quantities are closed results; check whether the actual d2 endpointfactor reduces to them, and if so APPLY their accepted lower bound with a proved bridge. Alternatively advance the exact moving-residue continued-fraction gap using the actual forced recurrence; generic algorithms and rational geometry do not imply the gap. Seek an actual infinite subexponential-weight obstruction or explicit family, not another sufficient unproved lemma as the primary contribution. Retain correct full F(n), complete logarithm, both endpoints+1, allgcd and wholeerror; distinguish nonvanishing ofomega from nonvanishing ofwholeform. No more exhaustive finite weight-window enumeration.''',
 [R/'responses/A3_turn7.md',R/'responses/A3_turn6.md',R/'responses/A3_turn5.md',R/'responses/A4_turn16.md',C/'homogeneous_budget_audit_receipt.json',D/'reviews/main_review_evidence/MAIN_ORTHOGONAL_REFERENCE_RECONSTRUCTION.md',D/'work/session_20260913/unequal_degree_hp_attempt.md'],gate)

make('A5',17,'''Your turn16 binary adjoint/one-variable formulas are pending separate audit. They still require b coefficients. Advance a genuinely compressed ADJOINT-MOMENT quotient, enough to evaluate at least one actual original norm and mixed pair at certified precision, or prove an invariant of their relative output. A concrete algebraic route worth resolving: H^T has binomial-coefficient band entries lambda_s binom(j+s,s), i.e. divided-power differential action. Its offidentity coefficients are even, so only M contact factors survive mod2^M. Conjugate the actual binomial transforms to polynomial/differential operators and ask whether the adjoint of the small Newton first-column producer closes in a precision-sized space of binomial-product/moment sequences, with only the bounded finite endpoint correction added. If it closes, give exact operators, integral basis, paid factorial/unit precision and finite transfer matrices; if it does not, identify a true obstruction and a feasible replacement, not generic2^poly(M)existence or original-length recurrence. A periodic backward band recurrence is another possible fast route, but its forcing and both binomial transforms must also be compressed, and period growth/state count quantified. The smallest actual u0 hasmu7, so raw target at least20bits before any additional normloss. Design a safe feasible arithmetic certificate instead of a b-row allocation; retain arbitrary precision and originalb=9^(18+32u). Do not re-evaluate the four initial zeros or the closed mod128table as a substitute. Seek a preserved norm/mixed relation underb->9^32b after true norm cancellation. Full normalized r, boundarythirdcolumn, endpoint+1, shortenedblock, fullgcd and wholeerror remain obligatory.''',
 [R/'responses/A5_turn16.md',R/'responses/A5_turn15.md',R/'responses/A5_turn13.md',R/'responses/A4_turn18.md',C/'COORDINATOR_COLUMN_NORMALIZATION_MAP.md',C/'normalized_binary_finite_audit_receipt.json',C/'weighted_force_audit_coordinator.py'],gate)

make('A4',19,'''Independently audit the complete A3turn7 diagonal forced recurrence, exact logarithmic contact/terminal-plane formula, sharper strip and denominator-stability scope, Wronskian/realtail bound, selectedprimepole/nonvanishing, actual two-stage target, proposed continued-fraction gap implication and fullgcd unselected-endpoint lowerbound. Reuse classical Legendre companion DLMF14.7.4 ratherthan claim novelty. Audit A5turn16 binary band+boundary factorization and all inverse-transpose orientations, endpointq, one-variable normalized mixed coefficient extraction with valid-term guards, normcutoff, supplied auxiliaryratio digits and original unitpivotf1, every raw/relativeguard digit. The personally authored central-force evaluator is now attached, repairing the previous packet's missing import; full prior coordinatecertificate also attached. If any algebraic or precision flaw occurs, derive a corrected statement and practical consequence. Give a justified route toward actual relative outputs or an actual d2 allprime endpoint-growth bridge if available; do not infer alignment from unit contact solves or small force initials. Complete finite boundaries, allterms,+1,fullgcd and wholeerror mandatory. No tools or proposed code execution; any bounded mathematical calculation may be described for coordinator inspection.''',
 [R/'responses/A3_turn7.md',R/'responses/A5_turn16.md',R/'responses/A4_turn18.md',C/'weighted_force_audit_coordinator.py',C/'normalized_binary_finite_audit_coordinator.py',C/'normalized_binary_finite_audit_certificate.json',C/'homogeneous_budget_audit_receipt.json',D/'reviews/main_review_evidence/MAIN_ORTHOGONAL_REFERENCE_RECONSTRUCTION.md'],gate)

(C/'ADJOINT_TERMINAL_OVERLAP_GATE.md').write_text('# Scoped primary and archive gate\n\n'+gate+'\n')
