from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D

gate='''Focused archive searches found earlier Krylov/Smith, spectral rank and Hankel inverse results, but no evaluated actual relative-pair law for the attached residual displacement. Fresh primary searches returned Bostan--Jeannerod--Mouilleron--Schost arXiv1703.03734 (official abstract opened: structured companion-displacement algorithms over fields, not arithmetic nonvanishing), and the already checked Rowland--Yassawi JTNB2015 DOI10.5802/jtnb.901 prime-power automata. The ETH Gragg/Gutknecht Hankel/Bezoutian PDF was located in search but full fetch failed; do not rely on an unchecked specific theorem from it. General structured/Hankel/Bezoutian and prime-power digit methods are classical overlap and must be reused. The new targets are the exact supplied original residual pair and normalized unit-sensitive Gram transfer; no equivalent specialized all-depth law was located in this scoped search. No exhaustive novelty claim is made.'''

make('A1',11,'''A4turn17 now ACCEPTS your turn9 exact eta/chi and producer precision theorem. Your turn10 terminal feature/return/displacement theorems are NEW pending audit. Advance the ACTUAL displacement-relative pair, retaining the full endpoint blockB_WZ. A concrete possibility: D=C-e0*l^T is unit-upper-Hessenberg, so its Krylov basis frome0 should have unit determinant; exploit that before any normalization loss. Derive the actual generating polynomials/resultant or structured Schur recurrence controlling detPsi and the complete distinguished bordered cofactor, with explicit actual last companion equation and endpoint transport. Classical rank2displacement/Bezoutian inversion is literature overlap, not a new nonvanishing theorem; do not infer invertibility from rank2orcyclicity. Evaluate the additional actual coefficients/returns needed and their precision losses, aiming at a genuine relative valuation or radical/nonvanishing theorem on the infinite original window. If the route reduces exactly to an already archived rational approximant, identify it and use its proved denominator/error obstruction instead of rebuilding it. Another formal determinant ratio, a general conditional coprimality statement, or a bulk solver of lengthn is insufficient as the main result. Full factorial functional, all20boundary features, actual endpoint-1, finite HIGH bounds and all-prime primitive form remain mandatory. A synthetic finite check may inspect algebra but cannot supply actual original divisibility.''',
     [R/'responses/A1_turn10.md',R/'responses/A1_turn9.md',R/'responses/A1_turn8.md',R/'responses/A4_turn17.md',C/'scalar_displacement_audit_receipt.json'],gate)

make('A2',8,'''Your turn7 band/endpoint transfer and two-scalar reduced force law are NEW pending audit. Its two binomial transforms still have original-length ranges and cannot yet be executed on the huge original producer. A5turn15 supplies a normalized binomial-product digit-transfer construction; it is pending audit, attached for careful cross-reuse. Advance the actual29Gram law by compressing the entire contact-word/Gram sums to a finite29digit transfer, including odd-prime factorial units and exact preferred original digits, then seek an invariant makingchi+N*(alpha-29rho) in29^2*NZ29 at the depth of the TRUE primitive norm. Merely proving generic automatic evaluability or restatingchi=M-... will not prove the law; give an actual conserved bilinear form, quotient transition relation, or original-family induction with all unit information. Alternatively prove a correctly scoped original-family obstruction to this alignment via a nonzero actual normalized defect. No new digit restriction may replace the preferred family without proving original reachability and retaining analytic windows. Fixed-degree skew route is closed. Keep complete initialr0,r1, saturated weighted lattice, both projection charges, shortened block, norm cancellation and final all-prime denominator/whole error.''',
     [R/'responses/A2_turn7.md',R/'responses/A2_turn6.md',R/'responses/A5_turn15.md',R/'responses/A4_turn17.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md',C/'scalar_displacement_audit_receipt.json'],gate)

make('A5',16,'''Your turn15 normalized digit-transfer/saturation theorem is NEW pending independent audit. Advance beyond generic evaluability to an ACTUAL original-family norm/mixed transfer invariant, or a concrete evaluated relative residue that can guide/prove it. Coordinator's own normalized finite audit is attached: exact complete contact residuals atb81,n324162 andb209,n836418 modulo2^13;rawVw is zero dueb! while4Y has nonzero residues; first/second contents and whole norm/mixed rawresidues retained. These are AUXILIARY, not original indices. Originalu0..3 complete initial f0/R,f1/R andr0,r1 are independently computedmod8192; r0,r1 are0atallfour, exact source-tail/log budgets included. Use these actual initial data with the three-column displacement and actual Gram, not a conclusion from four zeros. A potentially useful specialized step is a one-variable norm/mixed contraction after the complete Newton inverse filtration, retaining its small-degree producer and genuine large-index moment kernels; this may be much smaller than expanding all Neumann words into O(M)variables. Derive a tractable exact recurrence/transfer for that specialized contraction, unit-sensitive and with actual content losses paid. Seek a preserved bilinear relation underb->9^32*b, a transition quotient, or a rigorously evaluated defect. Generic2^poly(M)existence alone does not evaluate the law or guarantee feasibility. Reuse all closed fixed-depth results rather than requesting another mod128table; true variable target includes at least2mu+6 rawbits. Never infer norm primitivity from column primitivity. Full endpoints+1, shortened block, factorial/log terms, allprimegcd and whole nonzero error remain necessary.''',
     [R/'responses/A5_turn15.md',R/'responses/A5_turn13.md',R/'responses/A2_turn7.md',R/'responses/A4_turn17.md',C/'COORDINATOR_COLUMN_NORMALIZATION_MAP.md',C/'normalized_binary_finite_audit_receipt.json',C/'normalized_binary_finite_audit_coordinator.py'],gate)

make('A4',18,'''Independently audit A1turn10 actual terminal representer, tau/gamma reduction, normalized K/3integrality before final/9, explicitLOW/HIGH convolution orientations, two-digit terminal precision and producerp+9budget, whole residual displacementD=C-e0*l^T and completeendpointB_WZ relation. No residual invertibility may be presumed. Audit A2turn7 finite contact factorizationA=P*T*(H+LE)*T, alltailindices, unitendpointmatrix, projectedGram charge term, unweighted saturation and reducedforcechi numerator criteria including every guarddigit. Explicitly delimit boundedwidth versus original-length binomial transforms. Audit A5turn15 normalizedforce tail, normalizedlogbudgetKnorm>=b, finiteinverse binomialword expansion, high-index unit-sensitive digit-transfer lemma, exactcounting/flush/affineboundarysigns and statebound; distinguish generic existence from practical execution and actualalignment. The own coordinator normalized binary certificate includes two complete auxiliary systems and four ORIGINAL normalized initial-force pairs; verify scope, don't infer normlaw from zeros. Give corrections and one justified actual relative consequence if possible. Your accepted scalar/displacement/rawnormalization and weightedtail audits remain inforce; do not replaythem. Preserve original indices, fullforce,+1,leastclearer,fullgcd and same-indexwholeform.''',
     [R/'responses/A1_turn10.md',R/'responses/A2_turn7.md',R/'responses/A5_turn15.md',R/'responses/A4_turn17.md',C/'normalized_binary_finite_audit_receipt.json',C/'normalized_binary_finite_audit_coordinator.py',C/'homogeneous_budget_audit_receipt.json'],gate)

(C/'RELATIVE_STRUCTURE_OVERLAP_GATE.md').write_text('# Focused overlap gate — actual displacement and normalized transfers\n\n'+gate+'\n')
