from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_next_packets import make, R, O, C, D

gate = '''The scoped current archive check is restricted to mathematical Markdown registers, not provenance HTML embeddings. Previously accepted prime-power digit and finite rational-diagonal methods are reused. The primary literature includes Rowland--Yassawi, Automatic congruences for diagonals of rational functions, JTNB27(2015), DOI10.5802/jtnb.901, https://jtnb.centre-mersenne.org/item/10.5802/jtnb.901.pdf; Bostan--Christol--Dumas, https://arxiv.org/abs/1602.00545; and the newer prime-power state-complexity paper https://arxiv.org/abs/2408.00750. These are background methods, not a theorem that the actual parameter-dependent weighted/contact kernel has feasible state size. The actual monodromy and complete residual layers below are new supplied calculations requiring review; no exhaustive novelty claim is made. Reuse any exact overlapping identity rather than rederive it as new.'''

def audit():
    make('A4', 21, '''Independently audit A1turn12's complete depth18 residual divisibility, support-gap P19 proof, polynomial inverse transfer with the precision11 saturated producer jet, restoration of the COMPLETE producer remainder, all20features, exact coefficient-window formula, endpoint action and determinant-pair rescaling. A1turn11 was accepted by your turn20; preserve all finite boundary blocks, and do not treat determinant rescaling as a dimension-multiplied primitive-denominator gain. Check especially whether P19 support separation suffices after actual jet multiplication and inversion and whether any purported integral Schur perturbation is divided at unproved precision.

Independently audit A2turn9's all-phase monodromy (exception phase1 has rank2/index3), complete source at actual b=29B+27, shortened endpoint, the sharper58K+1 propagation bound, rational source/particular generating kernels and projected weighted Gram. The coordinator independently authored an exhaustive all29phase certificate BEFORE receiving turn9: every59step word zero mod29, hence59K uniform forgetting;60 higher-precision checks pass. Compare this with58K+1 and certify which bound is justified, without turning recurrence forgetting into Gram alignment. Source and certificate are attached for inspection, not remote execution.

Audit A5turn18's finite binomial transforms and constant-term formulas with W_j^2, exact boundary polynomial pairing, original Q=R^TR terminal b^2W_b^2, characteristic-zero Vandermonde obstruction and its precise lack of implication modulo2^M. Also audit the coordinator's actual original binary u0 operator/endpoint identity certificate atM20 (153 inverse coefficients/2926 high-index boundary identities; not a norm-pair computation). If a source identity fails, give a corrected exact statement and its impact. Prioritize decisive math and precise scope; no irrationality proof is claimed by these packets.''',
         [R/'responses/A1_turn12.md', R/'responses/A2_turn9.md', R/'responses/A5_turn18.md',
          R/'responses/A4_turn20.md', C/'odd29_nilpotent_memory_coordinator.py',
          C/'odd29_nilpotent_memory_receipt.json', C/'original_binary_operator_audit_coordinator.py',
          C/'original_binary_operator_audit_receipt.json'], gate)

def advance():
    make('A1', 13, '''Turn12 is in independent review. Its next-digit saturation bottleneck is already covered by the accepted general saturation theorem in yourturn5 andturn7, which are now attached in full. On t=5 the minimum k with5+v3(k!)>=6+12 is27, the same tail length as precision11. Therefore compare the actualB12 and chosenB11 lifts with the same monic factor before dividing by3^11; derive the next zero layer without pretending a new upstream numerical producer has been computed. Do not spend the whole report repeating the one-digit deduction. Use the general factorial tail theorem to find the strongest precision-parametrized ACTUAL Schur forgetting/vanishing theorem attainable by your finite polynomial inverse transfer. State explicit simultaneous conditions on P, saturationp, kappa_p, D andH; preserve original finite degrees, upper-gap budget, and complete nonlinear remainder. Determine where this method must lose its support separation, and what the first potential surviving coefficient window looks like there. Can the factorial tail plus finite core transfer force a usable relative determinant/cofactor valuation, or only successive common zero layers? Give a definite exact theorem or quantified obstruction. It is essential not to convert common dimension-scaled divisibility into a primitive denominator gain. Complete producer, endpoint and allprime gcd remain obligations.''',
         [R/'responses/A1_turn12.md', R/'responses/A1_turn5.md', R/'responses/A1_turn7.md',
          R/'responses/A1_turn8.md', R/'responses/A4_turn20.md'], gate)
    make('A2', 10, '''Turn9 is in independent review. Coordinator independently established59K finite memory before receiving your sharper58K+1 proof; reuse your exact symbolic monodromy, no further generic Fitting theorem or finiteprefix repetition. The present task is the specific head-to-source output kernelPsi_l in turn9(11.2), with complete finite contact inverse and tridiagonal squared weights. Seek an ACTUAL adjoint telescoping identity, finite boundary-aware rational coefficient representation, or a concrete obstruction to such an output-relative identity. Both homogeneous first-force columns vanish after2+58K in the INPUT recurrence, while the inverse contact operator remains nonlocal; exploit this bounded first-force support and the full divided-power contact factorization rather than replacing Gamma by a local matrix. The actual source is two equal impulses at26,27mod29 whose interior effect survives, so block-end zero is forbidden as a proxy. Derive the finite end contribution and the actual remaining high-index coefficient target. If state extraction is needed, use fixed-variable rational/Cartier machinery from checked primary literature with parameter exponents kept exact, and quantify costs; another generic29^poly(K) existence claim is insufficient. A complete source-output equality modulo29^(v29(N)+2) would resolve the local law only. Retain fullinitialr, logprotection, shortenedendpoint,+1 and true norm digit, and do not define rho byM/D.''',
         [R/'responses/A2_turn9.md', R/'responses/A2_turn7.md', R/'responses/A2_turn8.md',
          C/'odd29_nilpotent_memory_receipt.json', C/'odd29_nilpotent_memory_coordinator.py',
          C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md', R/'responses/A4_turn20.md'], gate)
    make('A5', 19, '''Turn18 is in independent review. Target the exact specialized modular weighted-extraction lemma in itssection8 using the actual coefficients and binary digits at ORIGINALu0, M20, m76. The coordinator independently generated the actual interior operator and2926 original high-index endpoint-commutator identities, allzero, but did NOT compute the Gram pair. Receipt and personallyauthored source attached. Your characteristic-zero Vandermonde obstruction is accepted only at its exact scope and doesnotruleout fixedprecision. Apply known fixed-variable Cartier/diagonal methods, including Rowland--Yassawi2026 prime-power state representation if useful, rather than inventing a generic automaton existence theorem. A promising direction is to lift the varying large powers (1+u)^(n+2),(1+v)^(n+2), and(1+Xy)^(-n) into coefficient targets of a fixed-denominator rational function; use integral finite-binomial sum encoding to retain b-1-i. Give actual denominator degrees, reachable state/linear-scheme bounds, and an honest concrete cost at20bits. Use the bounded number of weight multiplications actuallyneeded and exploit76degree dividedpowerinverse/endpointrank. If manageable, provide inspectable explicit computation for actualraw4N,8H mod2^20; otherwise identify a precise quantitative state-growth obstruction and give a narrower computable output certificate. Never execute tools here. Do notrepeatordinaryjetfailure, endpointfreeinfiniteinverse, or claim the interiorcertificate is a normlaw. Complete mixedforce, norm cancellation, logbudget, endpoint+1, finalshortblock, fullgcd andwholeform mandatory.''',
         [R/'responses/A5_turn18.md', R/'responses/A5_turn17.md', R/'responses/A5_turn16.md',
          C/'original_binary_operator_audit_coordinator.py', C/'original_binary_operator_audit_receipt.json',
          C/'COORDINATOR_COLUMN_NORMALIZATION_MAP.md', C/'weighted_force_audit_coordinator.py',
          R/'responses/A4_turn20.md'], gate)

if __name__ == '__main__':
    if '--advance' in sys.argv:
        advance()
    else:
        audit()
    (C/'MEMORY_KERNEL_OVERLAP_GATE.md').write_text('# Scoped gate for finite-memory and complete weighted coefficient kernels\n\n'+gate+'\n')
