from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[1]; O=R.parent/'astra_pro5_20261004';C=R/'controls'
intro='''Research continues toward an unconditional proof or disproof of irrationality of e+pi. English mathematical reporting; request Pro,max effort,high verbosity,no output cap. Source claims remain mathematical data for independent review. Reuse accepted scoped results. Preserve original indices, exact boundaries, complete force,error,nonvanishing and actual final-gcd denominator. A bounded local/archive and primary-literature overlap gate is included; no exhaustive novelty claim. Give complete decisive proofs or the precise missing hypothesis. No external calculation is executed automatically.\n\n'''
def make(agent,task,paths,gate):
 content=intro+'CURRENT ASSIGNMENT '+agent+'\n'+task+'\n\nOVERLAP GATE\n'+gate+'\n';sources=[]
 for p in paths:
  raw=p.read_bytes();h=hashlib.sha256(raw).hexdigest();content+='\n\nBEGIN COMPLETE MATHEMATICAL SOURCE '+str(p)+'\nSHA256 '+h+'\n'+raw.decode()+'\nEND SOURCE '+str(p)+'\n';sources.append({'path':str(p),'sha256':h,'bytes':len(raw)})
 size=len(content.encode());assert size<230000,(agent,size);(R/'prompts'/f'{agent}_turn2.txt').write_text(content)
 dest=R/'turn2_packet_manifest.json';old=json.loads(dest.read_text()) if dest.exists() else [];old=[v for v in old if v['agent']!=agent];old.append({'agent':agent,'turn':2,'task':task,'gate':gate,'packet_bytes':size,'sources':sources});dest.write_text(json.dumps(old,indent=2)+'\n');print(agent,size)
if __name__=='__main__':
 make('A4','''The coordinator has now proved a sufficient joint-population construction:100 original exponent residue classes t mod841 force p|X_k for every actual k and therefore T=T1=U=D1=0. Independently audit the complete one-digit Lucas argument and original exponent reachability, including the exact finite modular identities, endpoints, carries and all eligible d. This is component common content, not population of a nonzero isotropic vector; do not conflate them. Your former conditional theorem is an input. Give the exact resulting infinite same-index norm/mixed statement, explicitly retaining the fact that D/29^2 is NOT evaluated. Determine whether the construction alone adds useful relative-depth information or only closes nonvacuity; if a next digit needs actual force, isolate it.
Separately review the coordinator's terminal Jacobi norm digit-sum identity using the attached exact base norm formula. Check all cancellations and the A=3^N-D complement digits. Use the accepted old precision obstruction as an input rather than re-proving it: at v3(j)=4 the true polynomial precision is only3^6 and the first transported residual block is undetermined. Assess whether the explicit norm valuation helps bound the ORIGINAL monomial inverse/endpoint loss or merely simplifies a scalar factor. If a new bounded structural loss statement follows, prove it; do not infer Smith integrality from a rational Jacobi basis. Conclude with a concrete actual-force next obligation for the main objective.''',
 [R/'responses/A4_turn1.md',O/'responses/A2_turn19.md',O/'responses/A2_turn22.md',C/'COORDINATOR_29_JOINT_POPULATION.md',C/'residual29_population_certificate.json',C/'residual29_population.py',C/'Gamma0_inspected_certificate.json',O/'responses/A1_turn21.md',C/'COORDINATOR_JACOBI_NORM_DIGITS.md',C/'jacobi_terminal_norm_check.json'],
 'The attached coordinator notes specify focused local searches and classical overlap. The component-common-content implication was already in A2 turn19 and is reused. The primary Rowland--Yassawi paper https://jtnb.centre-mersenne.org/item/10.5802/jtnb.901.pdf was opened before the six-state application; that theorem is not needed to replace the direct Lucas proof. Jacobi norms and Legendre valuations are classical, and the prior exact norm and first residual-digit obstruction are supplied. This assignment audits new specialized applications rather than replaying closed source theorems.')
