from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_next_packets import make, R, O, C, D

gate = '''Focused local searches of the retained registers and current continuation locate the already accepted finite precision results, core-only singularity, complete endpoint producer, and ordinary rational-reconstruction uniqueness. Reuse them rather than repeating their proofs. Fresh primary-source overlap checks opened NIST DLMF 18.2 (general moment/orthogonality and Hankel methods) and Zelo arXiv:0903.0086 (fixed-family simultaneous real/p-adic approximation). Neither displayed source supplies the specialized moving actual residue or factorial-normalized signed producer application here. The prior opened generalized derangement Hankel paper arXiv:2402.16160 does not automatically supply even-subsequence rank-one normalization. Granville's primary factorial stripping and Lucas/Kummer are reused. This is a focused application gate, not an exhaustive novelty claim.'''

make('A1', 6, '''Your turn5 factorial-saturated producer and vanishing strip theorem is pending independent review; preserve its hypotheses and rank-one scalar denominator. Advance the ACTUAL next residual operator after the depth-seven digit C7, rather than another core-only rank statement. The original degree endpoint and ten-coefficient terminal jet modulo27 must remain exact. Determine whether this jet can be evaluated uniformly from the normalized unit matrix and its exact scalar response, preferably through finite Pascal residue elimination or a recurrence for the terminal solution. Then use the complete corrected-column force, LOW cross terms, all poles through mod27, HIGH return and carries to determine the next operator on the actual radical, with its transported endpoint. A whole-zero branch D<H/2916 may be a useful sharply specified domain; do not infer its original-index infinitude from unproved restricted digits. A rigorous cancellation/localization theorem that removes the terminal jet from the actual radical force would also be decisive. Do not merely restate the generic Schur compression or rename the unknown jet. Keep the primitive determinant pair, all-prime gcd, nonvanishing and whole evaluated error visible; report exactly what is and is not learned about them. Give derivation details sufficient for independent audit.''',
     [R/'responses/A1_turn5.md', R/'responses/A1_turn4.md', R/'responses/A1_turn3.md', R/'responses/A4_turn9.md', C/'ternary_radical_packet.json'], gate)

make('A3', 5, '''A4 turn9 now accepts the fixed-d cubic contrast and whole primitive-form divergence for the stated fixed weight progressions. Do not replay those excluded families. Advance your NEW exceptional resonant reconstruction problem for actual complete endpoints, starting with fixed d=2 and genuine indices n divisible15 or105. Derive a useful exact recurrence or closed expression for the actual v0 valuation and the actual rational residue Theta=-V/J at moduli approaching selected factorial depths. Your turn4 only bounds w_p below and proves sparsity, not absence or existence of useful short reconstructions. Determine whether short height weights with exponentially large H_gcd can occur in the real threshold window Lambda=n^2/2+(1-3sqrt2)n/2+O(1), and whether simultaneous local cancellation at3 and5 or3,5,7 can coexist with a nonzero improved whole error. A constructive candidate with full denominator/error estimates or a genuinely actual height obstruction would advance the objective. Do not apply a fixed-number Diophantine theorem to this moving residue without proving its hypotheses. You may propose bounded exact n=15,30,105,210 d=2 probes; the coordinator is independently computing full columns and general-weight gcd checks. Reuse the complete producer recurrence and outside +1. Avoid abstract rational-array counterexamples and another uniqueness proof. If arithmetic resonance is closed, investigate an actual alternative weight/functional justified by the supplied construction, with its full normalization.''',
     [R/'responses/A3_turn4.md', R/'responses/A3_turn2.md', R/'responses/A3_turn3.md', R/'responses/A4_turn9.md', C/'endpoint_extrapolant_coordinator.py'], gate)

make('A5', 8, '''The missing exact central-force formula is NOW attached in old turn20 equations2.1,2.2,3.1, together with your resumed turn1 and exact arbitrary-monomial contact implementation. Therefore do not stop at claiming the all-depth force is absent. Restore the complete actual precision-p force and contact inverse, with proven growing central/summation/forcing tails, and resolve the force-shift compensation you isolated at s=380,j=0 on the reachable branch v2(k+3)>=5. Your executive threshold>=4 was corrected inside the report to>=5; use the corrected theorem only. Compute or characterize the ACTUAL signed Newton coefficient p380 as k+3 approaches0, including finite inverse endpoints and all contact orders. If termwise compensation is false, seek a complete grouped identity before common-kernel division. Do not merely state force-weighted content by definition. Supply a coefficient-sensitive theorem or a complete bounded symbolic reduction with exact inputs, degree/precision bounds and a uniformity proof on original indices. The target remains N-2S divisible2^(2mu+4), or a rigorous counterexample/necessary correction for the actual complete columns. The separate model minimum-count computation is attached: all sixteen original counts are even. It is model-only and cannot replace the residual proof. Preserve full factorial/exterior tails, shortened terminal block, +1 and final odd-prime gcd. Do not execute supplied code; inspect its mathematical identities as source data.''',
     [R/'responses/A5_turn7.md', O/'responses/A5_turn20.md', R/'responses/A5_turn1.md', R/'responses/A5_turn6.md', C/'binary256_contact_coordinator.py', C/'kernel_minimum_multiplicity_certificate.json'], gate)

make('A4', 10, '''Independently audit the three newly completed specialized reports. Prioritize A1 turn5's normalized even-moment unit theorem, finite Pascal transformations, exact signed rank-one denominator, terminal pivot, scalar-integrality conclusion, factorial-tail localization, actual strip vanishing and ten-coefficient mod27 jet. Verify every original domain hypothesis and any division loss; this would transfer the reviewed core radical to the actual residual if valid. Audit A3 turn4's full companion divisibility by p^v_p(n), all general-weight gcd branches, resonance, actual-height sparsity and log-offset explicit whole-form divergence. The fixed-d analytic expansion has passed your turn9, so incorporate that reviewed result without redoing it. Audit A5 turn7's corrected >=5 shift obstruction, original-index reachability, odd multiplier, target-dependent logarithmic omission, growing factorial cutoff and finite inverse. Its missing full force inputs are separately assigned; do not turn framework formulas into an evaluated actual result. Also assess the supplied exact minimum-multiplicity certificate, distinguishing model content from actual norm. Identify errors with corrected statements, and pursue one concrete new consequence that materially advances an actual remaining bottleneck. No proof of e+pi irrationality has been obtained.''',
     [R/'responses/A1_turn5.md', R/'responses/A3_turn4.md', R/'responses/A5_turn7.md', R/'responses/A4_turn9.md', C/'kernel_minimum_multiplicity_certificate.json'], gate)
