from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D

gate='''Focused local searches of the main register and old response archive located classical resolvent/Schur methods, earlier normalized projections, fixed-digit closure and the original finite producer. Reuse these. No established specialized saturated full-force skew identity, nonlinear actual relative-pair theorem, or bulk-boundary coefficient380 evaluation was located in that scoped search. Fresh primary literature searches identified Berg--Szwarc arXiv:1801.06013 (infinite positive Hankel matrices, not this finite signed producer), p-adic factorial summation arXiv:1508.05079 (different series), and Rivoal JTNB DOI10.5802/jtnb.914 (already opened complete primary paper). They are methodological overlap, not proofs of the specialized moving-family statements. NIST DLMF18.2, Granville, classical Schur and suffix identities are reused. This is a focused application gate, not an exhaustive novelty assertion.'''

make('A1',8,'''Your turn7 exact nonlinear Schur identity and relative determinant-pair reduction are NEW and pending review. A4turn12 now supplies a specific qualification: the extended complete supported-return lemma at refined modulus3^6 was not independently proved, because the complete numerator and old propagation source were absent. The audit is attached, and the older propagation source is now supplied. FIRST discharge that formula-level obligation for the actual finite HIGH interval, full LOW subtraction, top-pole cancellation and factorial part. A width inequality or claim that an earlier proof extends is insufficient. This also gates any precision-parametrized support claim in turn7. Then advance the exact nonlinear term Q/3 and determinant pair: exploit the actual force's small terminal support, finite Pascal unit inverse, actual LOW inverse isotropy, and HIGH complement to identify a non-tautological structure or relative cofactor law. Do not merely rename Upsilon or state generic protection inequalities. The exact loss-aware identities of turn7 are useful, but D0,D1 nonvanishing and their relative valuation remain the actual target. A low-rank or finite terminal-jet representation with controlled omitted terms could be decisive if genuinely actual and uniform. If the proposed depth14 window rests on an undischarged stronger propagation lemma, keep it conditional until resolved. Do not claim a gain14nu after the common determinant powers cancel. Ordinary fixed-window original-index infinitude is already available; do not replay rotation proofs. Preserve actual producer endpoint, shortened residual dimension, full final gcd and whole same-index error. The coordinator will inspect the suggested small LOW isotropy calculation; it is auxiliary corroboration, not an actual asymptotic theorem.''',
     [R/'responses/A1_turn7.md',R/'responses/A1_turn6.md',R/'responses/A1_turn5.md',R/'responses/A1_turn3.md',O/'responses/A1_turn25.md',O/'responses/A4_turn26.md',R/'responses/A4_turn12.md'],gate)

make('A2',5,'''Your turn4 exact saturated projection and endpoint-normal current are new and pending audit. The complete-force skew-reconstruction identity7.7 remains open. Advance it using the actual force; do not re-prove normal charge, define s=M/D, or merely propose another unevaluated lemma. Analyze whether a bounded-degree nearest-neighbor skew family g_j=(j+1)(n+2-j)h_n(j) can satisfy the full force equality, including the explicitly nonintegral pullback xi at originally reachable deep branches. If this family is impossible, prove a precise actual obstruction, then develop a suitable saturated weighted operator or group identity that controls M-rhoD relative to D including additional primitive-norm cancellation. The outside+1, actual factorial/logarithmic force and all genuine finite endpoints must stay present. The fact that xi has unbounded negative valuation cannot be replaced by an assumed integral contact lift. It may instead constrain the independently determined scalar/operator coefficients. Seek exact force recurrences, commutator identities, or an actual norm/mixed factorization; abstract isotropic vectors and the old auxiliary scalar DP do not resolve this. Give an actual law or a sharp concrete reduction whose components can be evaluated, not a criterion defined from the desired defect. Full-gcd and whole-error implications remain obligatory. Suggested fixed factorial and F29 norm receipts will be personally checked by the coordinator.''',
     [R/'responses/A2_turn4.md',R/'responses/A2_turn3.md',R/'responses/A2_turn2.md',O/'responses/A2_turn20.md',O/'responses/A2_turn21.md',R/'responses/A4_turn11.md',C/'normalized29_compression_receipt.json'],gate)

make('A5',11,'''Your turn10 exact bulk-boundary decomposition and limiting vanishing through2^138 are new pending independent audit. A4turn12 separately proved a uniform actual-family precision96 vanishing via E^2(B1+B2+B3)=0mod2; reuse that accepted result. Advance the high-sector endpoint injection in exact recurrence7.1, using exact symbol factorial content, terminating force at h=-95 and telescoping bulk factorials. Determine whether the coefficient380 limit has a finite valuation or is identically zero. Do not label139 the first nonzero bit: it is merely the first admitted by the coarse bound. The coordinator will personally perform a bounded valuation-path screen at precision139 and provide a receipt if informative. You should derive a sharper analytic recurrence or factorization and quantify parameter continuity/local(k+3) divisibility, not wait for a dense inverse. The exact endpoint remainder has degree<s and may be low rank after generating-function summation; investigate whether all high-sector injections can be combined using actual b=-95/2001 and n=4002b. A proof that the complete tail has a controlled factor or a practical reduced coefficient computation would advance the bottleneck. If one coefficient cannot decide the full scalar residual, develop a grouped finite-suffix identity from the same decomposition. Preserve the second full force, exterior/logarithmic tails, shortened last block,+1, full scalar residual and final all-prime gcd. Avoid replaying the restored-force formulas except where needed to prove a new actual statement.''',
     [R/'responses/A5_turn10.md',R/'responses/A5_turn9.md',R/'responses/A5_turn8.md',O/'responses/A5_turn20.md',R/'responses/A4_turn12.md',C/'binary_limit_top_bit_certificate.json'],gate)

make('A4',13,'''Independently audit three new reports, prioritizing their actual uniformity and missing dependencies. A1turn7: inspect the exact nonlinear Schur identity, mixed-force factor3, LOW-inverse isotropy, actual Q/3 expression, transported endpoint, determinant-pair signs and primitive q formula. Determine precisely which claimed support/depth14 conclusions remain conditional on the stronger supported-return lemma you identified in turn12. The old full closure and intermediate source are now attached; do not waive the modulus requirement. A2turn4: verify exact normal charge and integral projector, both zero current boundaries, fixed B valuation arithmetic and original-index lifting producing unbounded negative contact-lift valuations, then the skew-reconstruction sufficient identity and its scaling. Distinguish genuine actual obstruction from a hypothesized relative alignment law. A5turn10: audit exact suffix/bulk-boundary decomposition, complete symbol factorial lower bound, changed force at negative continuation, the precision138 path proof including all endpoint injections and high input degrees, and uniform original-cylinder transfer. Seek one useful strengthened actual consequence rather than only verdicts. Your own accepted uniform actual precision96 result remains in force; the negative-limit bound is separate. Give corrections with derivations, and explicitly assess how any new result affects full norm/mixed/gcd arithmetic. Do not execute source code or use credentials.''',
     [R/'responses/A1_turn7.md',R/'responses/A1_turn3.md',O/'responses/A1_turn25.md',O/'responses/A4_turn26.md',R/'responses/A2_turn4.md',R/'responses/A5_turn10.md',R/'responses/A4_turn12.md'],gate)
