from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D
gate='''This is a continuation of supplied specialized producer and full-force results. Focused local archive checks locate the exact contact and hF definitions in old A2turn6, and the classical rank-one/Pascal/Schur operations. A mathematical source excerpt with original source hash is now supplied to close the previously missing entrywise logarithmic-force definition. Reuse all closed fixed-depth results. NIST DLMF18.2, Granville, the primary Rivoal simultaneous-Pade paper and classical rank-one moment modifications are overlap; no source already supplies the actual nonlinear relative-pair or saturated norm-factor channel law. No exhaustive novelty claim is made.'''

make('A1',9,'''Your turn8 refined propagation, Qdiv27 and bulk-boundary determinant-pair decomposition are NEW pending independent audit. A4turn13 already independently closed the coarser propagation needed by turn7; it is attached. Advance the relative arithmetic rather than another common zero digit. A potentially decisive smaller object is the signed producer denominator eta_n=F^2-uT*T^-1*u and scalar xi=chi/eta. The existing bounded exact probes at n5,8,11,14,17 gave v3(eta)=1, but this is auxiliary, not a law. Determine its actual original-family valuation or a finite Pascal/digit recurrence for eta and chi, retaining n=4^j+1,81|j,n2mod3. A proved uniform scalar precision could make the terminal jet and resulting boundary/bulk evaluable. If more useful, analyze displacement/return structure of the ACTUAL B^T*Hinv*B in your turn8 with all twenty boundary features and transported endpoint, to prove a relative cofactor law or nonvanishing. Do not infer nonsingularity from a formal Woodbury reduction. The producer scalar and full radical must remain exact, with any denominator loss explicitly paid. Do not spend the report just restating Psi or conditional small-matrix formulas. A controlled actual finite-state/recurrence theorem is useful if it computes the true pair rather than renaming unknowns. Full final gcd and whole evaluated error remain global obligations.''',
     [R/'responses/A1_turn8.md',R/'responses/A1_turn7.md',R/'responses/A1_turn5.md',R/'responses/A4_turn13.md',C/'even_moment_unit_certificate.json',C/'low_isotropy_certificate.json'],gate)

make('A2',6,'''Your turn5 nearest-neighbor obstruction and unit-only orthogonal factorization are NEW pending independent audit. A4turn13 now accepts the actual projection and contact-lift loss, and the coordinator independently verified both fixed arithmetic constants. Advance the actual transformed force-channel divisibility v in bmathfrak*Z29 or genuinely refute it; an exact coordinate change alone does not produce a norm factor. Exploit your complete factorial-force recurrence through the actual contact inverse, now with the COMPLETE entrywise logarithmic force definitions supplied in the source excerpt. Do not stop at claiming hF is unavailable or merely retaining it by a name. Evaluate the actual first-force combination2theta_(b-26)-theta_(b-25)mod29 on the preferred original cylinder, which decides whether the degree27 escape is immediately impossible; a vanishing scalar norm says nothing about this combination. If useful derive a saturated force adjoint/displacement identity tying that channel to the first-column norm, with independently determined coefficient and every finite endpoint. Nonintegral h with integral edges above degree26 remains an escape only if all force rows and high-precision matching are satisfied. Avoid another arbitrary isotropic example, general gcd formula, or new variable defined from M/D. Seek an actual all-depth relative theorem, a complete-force counterexample, or a reduced operator whose small data can be evaluated uniformly. Preserve common content plus primitive-norm cancellation, exterior+1,shortened block,least clearer,full final gcd and whole signed error.''',
     [R/'responses/A2_turn5.md',R/'responses/A2_turn4.md',R/'responses/A2_turn2.md',R/'responses/A4_turn13.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md',C/'normal29_constants_certificate.json'],gate)

make('A4',15,'''Independently audit A1turn8's refined full propagation and new nonlinear Qdiv27 claim, especially precision loss from dividing K(U,zhat)by3, support of actual LOW force modulo27, actual LOW inverse zeros, the terminal corner zhatmod9, inverse correction Cmmdiv3, lower-boundary return wdiv3, and all signs in the20feature bulk-boundary and bordered determinant pair. Your turn13 already closed coarser support; the sharper original domain must be checked formula by formula. Audit A2turn5's full factorial-force recurrence, nearest-neighbor contact pullback and integral-valued/degree<=26 actual impossibility, first degree27 matching residue, and exact unit-only orthogonal transformation. Determine whether its channel divisibility criterion is equivalent at all removed-content levels, preserving norm cancellation and fullforce. The complete contact/hF source excerpt and coordinator's fixed29/LOW arithmetic certificates are attached. Do not accept another unevaluated criterion as an all-depth alignment theorem. Give corrections and derive one concrete new actual consequence if possible. Your accepted binary high-tail compensation and A3 endpoint-height results remain in force; do not replay them. Full primitive/gcd/whole-error requirements remain unclosed.''',
     [R/'responses/A1_turn8.md',R/'responses/A1_turn5.md',R/'responses/A4_turn13.md',R/'responses/A2_turn5.md',R/'responses/A2_turn4.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md',C/'normal29_constants_certificate.json',C/'low_isotropy_certificate.json'],gate)
