from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D

gate='''This is audit/continuation of the supplied exact producer and displacement formulas. Scoped archive searches found the precise normalization X=Zw/(2R),Y=Vw/(4b!) in oldA5turn20, and the complete contact/hF excerpt. The coordinator derives an exact normalization map before assigning the next work. Classical Pascal/Hensel, divided-power, rank-one, linear ODE and finite displacement identities are literature overlap; Granville/Rowland-Yassawi prime-power digit methods and Rivoal2015 simultaneous Pade were previously checked. Reuse them. No supplied archive or primary result evaluates the requested actual relative pair or complete normalized three-column Gram law at all depths. No exhaustive novelty claim is made.'''

make('A4',17,'''Independently audit A1turn9 eta=chi=3mod9, finite shorter-class Pascal test vector, the complete-force cancellation, exact inverse/endpoint valuation and quadratic precision-protection solver. The coordinator independently implemented the finite Pascal lift through6digits at12orders including245, matched directmod3^11 scalar contractions andmod3^10 quotient, and checked fullchi; receipt and own source supplied. Audit A2turn6's nonzero29digit table/product, COMPLETE second-force terminal residue and global integral-valued/fixed-degree nearest-neighbor exclusion, full log homogeneity, exact finite displacement, three-column rational rank, and saturated adjoint criterion. Coordinator checked the29table by an independent coefficient formula and all displacement identities at four finite systems, with three-column rank3. Distinguish rational rank from saturated lattice. Audit A5turn14's whole logarithmic budget and raw Newton finite-state recurrence, then apply the coordinator's exact normalization map. Determine whether the algorithm actually reduces normalized4Y at precisionM or only rawVw at precisionv2(b!)+M. The old exact X/Y definitions and complete source are supplied. The earlier suggested b1,3 weighted-difference probes do not have k inZ2; own force receipt instead uses integral oddk,192complete-force differences and33153scalar checks. Do not use unsupported auxiliary parameters to validate an all-index claim. Give precise corrections, keep all contents/endpoints+1, and derive one new genuinely evaluable relative consequence if justified. Previously closed binary weighted-tail and A3splitting results remain accepted; do not replay them as the main report.''',
     [R/'responses/A1_turn9.md',R/'responses/A2_turn6.md',R/'responses/A5_turn14.md',O/'responses/A5_turn20.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md',C/'COORDINATOR_COLUMN_NORMALIZATION_MAP.md',C/'scalar_displacement_audit_receipt.json',C/'scalar_displacement_audit_coordinator.py',C/'weighted_force_audit_receipt.json',C/'weighted_force_audit_coordinator.py'],gate)

make('A5',15,'''Your turn14 raw second-column budget/Newton recurrence is NEW pending audit. The coordinator now supplies the EXACT normalization bridge missing from that report. RawVw=b!*(Rrec*A^-1*r+Wb*endpoint), so4Y=Rrec*A^-1*r+Wb*endpoint. Exteriore0 cancels the FULL finite factorial reconstruction before division; it does not become a different-coordinate+1 by fiat. Computing rawVw toP=v2(b!)+M gives degree proportional tob and is not a precision-sized normalized algorithm. Advance at normalized-force level using r=(h-A*facvec)/b! and its COMPLETE exponential tail q=b+t, whose t-tail is bounded byv2(t!) but whose lower binomial indexb+t is genuinely large. The old exact X/Y definitions, full source, and A2turn6 rational complete displacement/triple-column identity are attached for cross-reuse. Apply the latter in binary with independently justified saturation/content. Seek an actual O(poly(M)) or finite digit-transfer evaluation of the complete normalized low-sector Gram entries, with exact original binomial units, shortened block, endpoint+1 and logarithmic initial data afteralllosses. First-force f0/R is available through the accepted complete central filtration; do not move back to raw precision proportional ton. A proved kernel/digit contraction including high lowerindices is useful; simply low shift labels, a3x3Gram with unevaluated entries, or an algorithm polynomial inM+v2(b!) is not the requested reduction. Preserve primitive-norm cancellation and full final gcd/whole error. A4turn16 nowaccepts your weighted-tail/content theorem in the divided-power lattice; no repeatp380 or rawsecondsupporttheorem needed.''',
     [C/'COORDINATOR_COLUMN_NORMALIZATION_MAP.md',R/'responses/A5_turn14.md',R/'responses/A5_turn13.md',R/'responses/A4_turn16.md',R/'responses/A2_turn6.md',O/'responses/A5_turn20.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md',C/'weighted_force_audit_receipt.json'],gate)
