from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D
gate='''Focused archive register searches for monodromy, rank-one block reset and actual Hankel radical found other already accepted signed-moment and spectral constructions, not this actual newly normalized residual or recurrence law. Classical Hankel/Bezoutian, divided-power calculus and prime-power digit methods are reused from previously checked primary sources (Bostan etal arXiv1703.03734; Rowland--Yassawi JTNB2015; Granville). Primary DLMF14.7.4 identifies the logarithmic companion as classical and is reused. No scoped match for the specific actual normalized moment-minor or output-relative law was located; no exhaustive novelty claim. Any known generating-function or finite-ring Fitting theorem should be applied with its precise hypotheses, rather than reproved as a novel result.'''

make('A1',12,'''Your turn11 actual unit-resultant/Hankel transfer is pending independent audit. Advance the ACTUAL initial moments/forcing, not another general structured determinant representation. Evaluate the normalized complete moments modulo3 on the original depth16window from the complete producer correction, including all20features and endpointreturn. Seek an actual radical/rank and endpoint-action theorem for that leading Hankel form; if the leading form has huge radical, derive its next normalized induced form with rigorous precision, instead of presuming unit pivots. A possible route is finite prime-power producer jet plus coefficient/Lucas analysis for the whole Schur complement, followed by a moment generating function or finite recurrence. Your companion polynomial has huge repeated-root multiplicity mod3, so generic etale/simple-root arguments are excluded. The normalizer is now a proved unit; it is not a determinant nonvanishing proof. Aim at actualdelta0/delta1relativevaluation or exact original radical classification with completeboundarysubtraction. Do not end with the same unevaluated sufficient lemma as main contribution. If a finite precision computation is feasible, provide explicit original-data generation and bounded states; a synthetic3x3example only checks generalalgebra. Keep originalwindowreachability, fullfactorial/polefunctional, allprimegcd and wholeform.''',
 [R/'responses/A1_turn11.md',R/'responses/A1_turn10.md',R/'responses/A1_turn8.md',R/'responses/A4_turn18.md',C/'scalar_displacement_audit_receipt.json'],gate)

make('A2',9,'''Your turn8 sign-sensitive digit/Fitting and six-entryGram transfer is pending independent audit; generic stateexistence remains insufficient without actualrelativeoutput. Study a more restrictive actual recurrence reset: whenn=0mod29, at i=0mod29 beta_i=gamma_i=0 andalpha_i=1, thenati=1mod29 gamma_i=0,beta_i=1,alpha_i=3. Thus two adjacent steps send(h_i,h_(i-1),h_(i-2)) to(2h_i,h_i,h_i)mod29. Analyze the complete29-stepmonodromy, including source, actuallowdigits andphase, and lift this rank-one reset to higherprecision using the genuine finite-ring stableimage. Does it give a precision-sized input/output-compatible quotient, a conserved weighted bilinear form or actualnorm/mixeddefect? Derive actual transitionweights, projectors and boundarycharges ratherthan onlypowerperiod. Anyperiod29^K or29^poly(K)state bound must be quantified as potentially impractical; seek a simpler algebraic closure of the actual momentkernels or diagonal rationalgeneratingfunctions. Ultimately test/prove C-29rhoN in29^2NZ29 at the TRUE firstnonzeronormdigit onoriginalorbit b=3^(249005515+574312172u). Preserve completeinitialr, shortenedblock/endpoints+1, projectioncharges andnormloss. A rank-one internal recurrence alone does not implyGram alignment. Avoid fixeddepth table repetitions; any finite auxiliarycheck audits implementationonly.''',
 [R/'responses/A2_turn8.md',R/'responses/A2_turn7.md',R/'responses/A2_turn6.md',R/'responses/A4_turn18.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md'],gate)

make('A5',18,'''A4turn19 accepts your turn16 binaryadjoint formulas, with precise squared-column versusone-sidednorm guard digits attached. Coordinator personally regenerated the band/boundaryadjoint and highcoefficientmoments atb81,b209 modulo8192: allresiduals0,315 independenthighmomentcoefficientidentitieseach, rawoutputs4248/3888 and2240/2432; auxiliaryonly. Your turn17 compresseddivided-powerinverse and finite-translationobstruction are new pendingaudit. Complete the FIRST actualkernelclosuregate in turn17section6. Evaluate exact symbolic reductions ofbothfinitebinomialtransforms on an actualsmallfirstforcekernel, complete mixedkernel s=t=0, and boundarypolynomialpairing, with actualW_j^2/adjacentweights. Use finiteVandermonde/creative telescoping or a boundary-aware diagonal rationalrepresentation when valid. Give a finite basis with exact integral operators and explicitstate/dimension, or prove a specific closureobstruction and produce a feasible alternative. Ordinaryjetquotient is alreadyclosed; do notrepeatitscounterexample. Aim at an actualoriginalnorm/mixedcertificate atM>=20 or originalrelativeinvariant afterfullnormcancellation. The new differentialoperator alone does not evaluateeither output. Full r, logarithmicbudget, endpoint+1,shortenedblock and allprimeprimitiveerror mandatory.''',
 [R/'responses/A5_turn17.md',R/'responses/A5_turn16.md',R/'responses/A4_turn19.md',C/'binary_adjoint_audit_receipt.json',C/'COORDINATOR_COLUMN_NORMALIZATION_MAP.md',C/'weighted_force_audit_coordinator.py'],gate)

make('A4',20,'''Independently audit A1turn11 actualterminalgenerator residue,det1Krylov,f polynomial inclfinalequation,repeated-rootfactorization,unitresultant,integralHankeltransfer, endpointkernelcofactorwithfullB_WZ/csubtraction, andRprecisionp+10/inputp+17. Audit A2turn8 oddprimeunitsigns, binomial/normalizedforceguards, firstforcebinomialformula, uniformpowerquotientFitting(3K,PiK),intervalproductorientation, recurrenceparticularsource, six-entryGram/projection and exactoriginalreachability, true-normlogprotection. Audit A5turn17 interiorcompresseddivided-powerinverse,finiteendpointcommutatorandtranslationobstruction, closurekernels andprecision. Important COORDINATOR CORRECTION to yourturn19endpointgrowth wording and A3turn8assignment: A,B in the primitiveqformula are formed AFTER each complete endpointrow(Uj,Vj) is divided by its own rowgcd, thenfirstcomponents' commonh removed. Thus A,B depend on the complete secondforce through rowgcds, not onlyC^-1z. The attached personallyauthored terminalcertificate implementsthis correctly and reproduces archivedA,B; do notprovegrowth of rawfirstendpoint ratio and substitute it. New coordinator exactterminal/wronskianandbinaryadjointreceipts alsoattached, allboundedfinitePASS; noinfinitelawfromthem. Derivecorrected usable actualrelativeconsequence ifavailable. Fullforces,boundaries,+1,leastclearer,allgcd and wholeform remainobligations.''',
 [R/'responses/A1_turn11.md',R/'responses/A2_turn8.md',R/'responses/A5_turn17.md',R/'responses/A4_turn19.md',C/'terminal_companion_audit_receipt.json',C/'terminal_companion_audit_coordinator.py',C/'binary_adjoint_audit_receipt.json'],gate)

(C/'ACTUAL_KERNEL_OVERLAP_GATE.md').write_text('# Scoped overlap gate for actual moment/output laws\n\n'+gate+'\n')
