from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D

gate='''Focused current/archive checks locate the supplied finite Pascal unit theorem, signed rank-one producer, complete recurrence and adjoint/contact reductions. Do not repeat those. Primary overlap already checked: NIST DLMF18.2 classical moment/Hankel identities, Granville prime-power binomial methods, the primary Rivoal simultaneous exponential/logarithm Pade paper, and the fresh central-binomial Lucas search. Pascal/Hensel lifting, rank-one inverse contraction and linear differential splitting are classical tools, reused here. The actual endpoint-sensitive residual relative-pair theorem and complete unit-sensitive three-column Gram law were not located in this scoped check. No exhaustive novelty claim is made.'''

make('A1',10,'''Your turn9 eta/chi law and exact one-digit producer loss are NEW pending independent audit. A4turn15 now ACCEPTS your turn8 refined propagation, Qdiv27, depth16 pair and20-feature bordered decomposition at their original scopes. Its complete audit is attached. The coordinator independently checked eta valuations at31 finite orders modulo729 and the auxiliary80-vector LOW isotropy6400 pairings modulo27; both finite-only receipts are supplied. Advance the actual nonlinear BULK/endpoint relative pair, now with the true endpoint valuation2v3((n-1)!) and fully evaluable terminal producer jet. Use the full Schur return/displacement structure rather than another common zero digit, another formal Woodbury condition, or lifting an n-dimensional solver without reducing the decisive actual contractions. Determine actual nonvanishing and a relative cofactor valuation law, or prove a rigorous original-family obstruction that closes this determinant route at its whole-form scope. You may use the20-feature border but cannot assume the growing bulk is invertible; an exact singularity/radical conclusion is useful if justified on the full original residual space. A promising narrower target is the true terminal-channel inverse contraction with a certified precision loss independent of unknown determinant cancellation, using the actual LOW return and all finite HIGH boundaries. If a fixed-precision recursive block method computes that true relative pair, specify complete inputs, output and stopping criterion; merely defining a new unknown defect is insufficient. Preserve the signed complete functional, endpoint subtraction, cutoff, complete factorial contribution, least clearer,full gcd and whole evaluated error. Do not repeat the solved eta mod9 calculation as the main report.''',
     [R/'responses/A1_turn9.md',R/'responses/A1_turn8.md',R/'responses/A1_turn7.md',R/'responses/A4_turn15.md',C/'signed_eta_mod729_certificate.json',C/'low27_isotropy_certificate.json'],gate)

make('A2',7,'''Your turn6 complete-force displacement, actual29 terminal residues, fixed-degree nearest-neighbor exclusion and three-column reduction are NEW pending independent audit. A4turn15 already validates the earlier recurrence/source, channel transformation and corrected criteria after arbitrary content removal; its exact audit is supplied. Advance the actual reduced force norm-factor obligation rather than searching again for a fixed-degree skew operator now obstructed. Compute the UNIT-SENSITIVE Gram matrix of the three actual kernel columns or an equivalent boundary Green/Christoffel-Darboux contraction, ideally by an exact recurrence of order bounded by requested precision, preserving the true saturated reconstruction lattice. Your definitionsB0=R*A^-1*h0, B1=..., B*=R*A^-1*tau+endpoint are exact but do not yet evaluate the Gram entries. Exploit D*A=-V*C to turn the adjoint factorial boundary sum and endpoint into genuinely evaluable few boundary invariants, retaining complete r0,r1 and logarithmic initial data. Seek a proof or actual counterexample of E_force in29^3*bmath*Z29 and the corrected unit-scale congruence; if unavailable derive a non-tautological evaluable transfer law with explicit initial/unit data on the original exponential family. Do not identify three-dimensional rational rank with saturated integral rank, and do not infer a norm factor from an isometry. Reuse the proven J digit product and psi last residue; no new digit restrictions may silently replace the original cylinder. Full relative content, primitive norm cancellation, shortened terminal block,complete+1,all-prime gcd and whole nonzero evaluated error remain required.''',
     [R/'responses/A2_turn6.md',R/'responses/A2_turn5.md',R/'responses/A2_turn4.md',R/'responses/A4_turn15.md',C/'COMPLETE_CONTACT_FORCE_SOURCE_EXCERPT.md',C/'normal29_constants_certificate.json'],gate)
