from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_next_packets import make,R,O,C,D

gate='''Focused archive search locates the earlier p=23 branch in A2 turn6, the fixed29 digit contractions, all fixed binary interfaces, and ordinary telescoping/orthogonality machinery. Do not reopen the p23 branch as new. No exact all-depth actual defect current or evaluated p380 limit was located in the retained scoped search. The primary Granville factorial arithmetic, NIST DLMF18.2 and opened fixed-target real/p-adic thesis arXiv:0903.0086 are overlap; they do not supply these particular moving-force identities. A fresh primary search also identifies Rivoal's simultaneous exponential/logarithmic Pade paper (JTNB DOI10.5802/jtnb.914); its general methods are literature, not an automatic result for the supplied producer. This is a focused gate, with no exhaustive novelty claim.'''

make('A2',4,'''Your normalized higher-tail scalar is available and is pending independent audit; do not rerun the initializer or claim its nonzero seeds force original units. Advance the ACTUAL all-depth mixed-defect relation, preferably by constructing the proposed finite-boundary current or an integral skew-adjoint reconstruction identity whose scalar part is known independently of the norm. Work from the complete actual finite contact and force, not an abstract vector example. Track removed common content AND additional primitive-norm cancellation. If an all-depth relative alignment theorem is false, identify a genuine actual countermechanism with the full force and original endpoints; arbitrary isotropic vectors are already known insufficient and add nothing. An exact adjoint/commutator identity from the finite contact Toeplitz-Pascal system may be useful: preserve factorial boundary, exponential/logarithmic forcing, outside +1, and first/last high-block currents. Alternatively obtain an actual all-depth factorization with quantitatively controlled shift loss, or a full-gcd statement that resolves the final primitive denominator. The coordinator will audit the new scalar compression separately; do not spend the report repeating the DP classification, blockers, or uniqueness. Give a non-tautological derivation and specify its consequence for the actual D,M and whole same-index form.''',
     [R/'responses/A2_turn3.md',R/'responses/A2_turn2.md',O/'responses/A2_turn20.md',O/'responses/A2_turn21.md',O/'responses/A2_turn6.md',C/'onecarry29_certificate.json',C/'onecarry29_initialization_406.json'],gate)

make('A5',9,'''The complete growing force is now restored in turn8. Advance the coefficient-limit or grouped compensation rather than re-reporting an unevaluated finite algorithm. First exploit the precision-weighted degree filtration: contact-symbol order r costs at least r bits and adds at most4r degrees, while central/forcing tails themselves have index-dependent factorial depth. Determine a sharp bound for the surviving degree at precision p; the generic quadratic d_p is likely far too loose. Establish what precision can first allow coefficient380, with a proof including force tails and all finite endpoint operators. Then derive a computationally practical exact recurrence or closed identity for its limit at h=-95,n=-190,b=-95/2001. Do not substitute a negative-size matrix; only already justified polynomial continuation is allowed. Determine whether the limit vanishes identically or has a finite valuation, and if zero prove the quantitative k+3 divisibility needed for compensation. If that individual-term approach fails, find a complete grouped finite-suffix identity or a provable actual norm-content statement that avoids it. Provide auditable algebra and complexity/precision bounds for any genuinely useful proposed bounded calculation. The personally authored reachability certificate covers ell5..16 and agrees with the corrected shift theorem. Reuse those cases. Full scalar residual, mixed contraction and odd-prime final gcd remain open; aim to close one actual obstruction rather than another definition.''',
     [R/'responses/A5_turn8.md',R/'responses/A5_turn7.md',O/'responses/A5_turn20.md',R/'responses/A5_turn1.md',C/'binary256_contact_coordinator.py',C/'binary_shift380_certificate.json'],gate)

make('A4',11,'''Audit A2 turn3's higher-tail scalar completely: coefficients from the exported initializer, both tail endpoints R/R-1, the mandatory2C+1 carry, all-digit polynomial product, actual relative-valuation implications, blocker quantifiers, and any hidden division or endpoint loss. Its all-depth actual current remains conjectural; do not accept a criterion as construction. Also independently audit A5 turn8's all-precision force restoration, central/forcing cutoffs, arbitrary-order finite operator, coefficient-valued inverse, continuity/compatibility at the negative p-adic parameter and claimed denominator-cylinder bound. Seek the sharp precision-weighted degree bound and verify whether coefficient380 can actually appear at16/32 bits before requesting a large computation. Assess the coordinator's three new exact audits:41 normalized matrix orders and6 signed producer cases,96 actual full-gcd endpoint weight probes across n15,30,105,210,d2, and12 actual reachable shift classes. They are finite corroboration, not asymptotic proof. Supply corrected statements for any flaw, and derive a concrete new actual consequence or narrower next lemma. Your turn10 support theorem is retained; A1 is separately working its corrected-column force.''',
     [R/'responses/A2_turn3.md',R/'responses/A5_turn8.md',C/'onecarry29_initialization_406.json',C/'onecarry29_certificate.json',C/'even_moment_unit_certificate.json',C/'general_endpoint_weights_receipt.json',C/'binary_shift380_certificate.json',R/'responses/A4_turn10.md'],gate)
